"""Initial migration

Revision ID: 247a8f73e9bb
Revises: 
Create Date: 2026-04-05 12:40:10.639864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '247a8f73e9bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('superadmin', 'employee', 'user', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('labour_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('skills', sa.String(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labour_services_id'), 'labour_services', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('labour_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'completed', 'cancelled', name='bookingstatus'), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['labour_id'], ['labour_services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.drop_index(op.f('payment_bookingId_key'), table_name='payment')
    op.drop_index(op.f('payment_userId_idx'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('review_bookingId_key'), table_name='review')
    op.drop_index(op.f('review_equipmentId_idx'), table_name='review')
    op.drop_index(op.f('review_rating_createdAt_idx'), table_name='review')
    op.drop_index(op.f('review_reviewerId_idx'), table_name='review')
    op.drop_table('review')
    op.drop_table('spatial_ref_sys')
    op.drop_index(op.f('notification_userId_idx'), table_name='notification')
    op.drop_table('notification')
    op.drop_table('_prisma_migrations')
    op.drop_table('verification')
    op.drop_index(op.f('user_city_state_idx'), table_name='user')
    op.drop_index(op.f('user_email_idx'), table_name='user')
    op.drop_index(op.f('user_email_key'), table_name='user')
    op.drop_index(op.f('user_isVerified_idx'), table_name='user')
    op.drop_index(op.f('user_latitude_longitude_idx'), table_name='user')
    op.drop_index(op.f('user_role_idx'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('_ConversationParticipants_B_index'), table_name='_ConversationParticipants')
    op.drop_table('_ConversationParticipants')
    op.drop_index(op.f('session_token_key'), table_name='session')
    op.drop_index(op.f('session_userId_idx'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('conversations_bookingId_key'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('dm_conversations_participant1Id_participant2Id_key'), table_name='dm_conversations')
    op.drop_table('dm_conversations')
    op.drop_index(op.f('disputes_bookingId_idx'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('booking_equipmentId_idx'), table_name='booking')
    op.drop_index(op.f('booking_labourId_idx'), table_name='booking')
    op.drop_index(op.f('booking_renterId_idx'), table_name='booking')
    op.drop_index(op.f('booking_status_idx'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('direct_messages_conversationId_idx'), table_name='direct_messages')
    op.drop_table('direct_messages')
    op.drop_index(op.f('message_receiverId_idx'), table_name='message')
    op.drop_index(op.f('message_senderId_idx'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('notification_preferences_userId_key'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('user_roles_userId_idx'), table_name='user_roles')
    op.drop_index(op.f('user_roles_userId_role_key'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('account_userId_idx'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('labour_profile_skills_idx'), table_name='labour_profile', postgresql_using='gin')
    op.drop_index(op.f('labour_profile_userId_idx'), table_name='labour_profile')
    op.drop_index(op.f('labour_profile_userId_key'), table_name='labour_profile')
    op.drop_table('labour_profile')
    op.add_column('equipment', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('type', sa.String(), nullable=False))
    op.add_column('equipment', sa.Column('hourly_rate', sa.Float(), nullable=False))
    op.add_column('equipment', sa.Column('daily_rate', sa.Float(), nullable=False))
    op.add_column('equipment', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.alter_column('equipment', 'id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('equipment', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('equipment_category_idx'), table_name='equipment')
    op.drop_index(op.f('equipment_description_idx'), table_name='equipment', postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('equipment_isAvailable_createdAt_idx'), table_name='equipment')
    op.drop_index(op.f('equipment_latitude_longitude_idx'), table_name='equipment')
    op.drop_index(op.f('equipment_name_idx'), table_name='equipment', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('equipment_ownerId_idx'), table_name='equipment')
    op.drop_index(op.f('equipment_pricePerDay_idx'), table_name='equipment')
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.drop_constraint(op.f('equipment_ownerId_fkey'), 'equipment', type_='foreignkey')
    op.create_foreign_key(None, 'equipment', 'users', ['owner_id'], ['id'])
    op.drop_column('equipment', 'isAvailable')
    op.drop_column('equipment', 'horsepower')
    op.drop_column('equipment', 'category')
    op.drop_column('equipment', 'latitude')
    op.drop_column('equipment', 'reviewCount')
    op.drop_column('equipment', 'brand')
    op.drop_column('equipment', 'longitude')
    op.drop_column('equipment', 'pricePerDay')
    op.drop_column('equipment', 'images')
    op.drop_column('equipment', 'ownerId')
    op.drop_column('equipment', 'createdAt')
    op.drop_column('equipment', 'totalBookings')
    op.drop_column('equipment', 'year')
    op.drop_column('equipment', 'features')
    op.drop_column('equipment', 'fuelType')
    op.drop_column('equipment', 'description')
    op.drop_column('equipment', 'rating')
    op.drop_column('equipment', 'model')
    op.drop_column('equipment', 'updatedAt')
    op.drop_column('equipment', 'locationName')
    op.drop_column('equipment', 'videoUrl')
    op.drop_column('equipment', 'pricePerHour')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('pricePerHour', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('videoUrl', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('locationName', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False))
    op.add_column('equipment', sa.Column('model', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('rating', sa.NUMERIC(precision=3, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('fuelType', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('features', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('totalBookings', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('equipment', sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('equipment', sa.Column('ownerId', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('equipment', sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('pricePerDay', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('equipment', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('reviewCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('equipment', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('category', postgresql.ENUM('TRACTOR', 'HARVESTER', 'PLOUGH', 'CULTIVATOR', 'ROTAVATOR', 'THRESHER', 'SPRAYER', 'SEEDER', 'IRRIGATION', 'DRONE', 'OTHER', name='EquipmentCategory'), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('horsepower', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('equipment', sa.Column('isAvailable', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.create_foreign_key(op.f('equipment_ownerId_fkey'), 'equipment', 'user', ['ownerId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.create_index(op.f('equipment_pricePerDay_idx'), 'equipment', ['pricePerDay'], unique=False)
    op.create_index(op.f('equipment_ownerId_idx'), 'equipment', ['ownerId'], unique=False)
    op.create_index(op.f('equipment_name_idx'), 'equipment', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('equipment_latitude_longitude_idx'), 'equipment', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('equipment_isAvailable_createdAt_idx'), 'equipment', ['isAvailable', 'createdAt'], unique=False)
    op.create_index(op.f('equipment_description_idx'), 'equipment', ['description'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('equipment_category_idx'), 'equipment', ['category'], unique=False)
    op.alter_column('equipment', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('equipment', 'id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('equipment', 'is_available')
    op.drop_column('equipment', 'daily_rate')
    op.drop_column('equipment', 'hourly_rate')
    op.drop_column('equipment', 'type')
    op.drop_column('equipment', 'owner_id')
    op.create_table('labour_profile',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('experienceYears', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dailyRate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('hourlyRate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('certifications', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('availability', sa.TEXT(), server_default=sa.text("'available'::text"), autoincrement=False, nullable=False),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('isVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('reviewCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('averageRating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('totalJobs', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('labour_profile_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('labour_profile_pkey'))
    )
    op.create_index(op.f('labour_profile_userId_key'), 'labour_profile', ['userId'], unique=True)
    op.create_index(op.f('labour_profile_userId_idx'), 'labour_profile', ['userId'], unique=False)
    op.create_index(op.f('labour_profile_skills_idx'), 'labour_profile', ['skills'], unique=False, postgresql_using='gin')
    op.create_table('account',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accountId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('providerId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accessToken', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refreshToken', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('account_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('account_pkey'))
    )
    op.create_index(op.f('account_userId_idx'), 'account', ['userId'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('RENTER', 'PROVIDER', 'LABOUR', 'ADMIN', name='Role'), autoincrement=False, nullable=False),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('user_roles_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_roles_pkey'))
    )
    op.create_index(op.f('user_roles_userId_role_key'), 'user_roles', ['userId', 'role'], unique=True)
    op.create_index(op.f('user_roles_userId_idx'), 'user_roles', ['userId'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bookingEnabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('paymentEnabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('messageEnabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('trustEnabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('securityEnabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('insightEnabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('systemEnabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('inAppEnabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('emailEnabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('smsEnabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('pushEnabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('quietHoursEnabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('quietHoursStart', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quietHoursEnd', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quietHoursTimezone', sa.TEXT(), server_default=sa.text("'UTC'::text"), autoincrement=False, nullable=False),
    sa.Column('allowCriticalDuringQuiet', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('digestMode', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('digestFrequency', sa.TEXT(), server_default=sa.text("'immediate'::text"), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('notification_preferences_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_preferences_pkey'))
    )
    op.create_index(op.f('notification_preferences_userId_key'), 'notification_preferences', ['userId'], unique=True)
    op.create_table('message',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('senderId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('receiverId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bookingId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('isRead', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('conversationId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('readAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bookingId'], ['booking.id'], name=op.f('message_bookingId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversationId'], ['conversations.id'], name=op.f('message_conversationId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiverId'], ['user.id'], name=op.f('message_receiverId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['senderId'], ['user.id'], name=op.f('message_senderId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('message_pkey'))
    )
    op.create_index(op.f('message_senderId_idx'), 'message', ['senderId'], unique=False)
    op.create_index(op.f('message_receiverId_idx'), 'message', ['receiverId'], unique=False)
    op.create_table('direct_messages',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('conversationId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('senderId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('isRead', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('readAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversationId'], ['dm_conversations.id'], name=op.f('direct_messages_conversationId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senderId'], ['user.id'], name=op.f('direct_messages_senderId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('direct_messages_pkey'))
    )
    op.create_index(op.f('direct_messages_conversationId_idx'), 'direct_messages', ['conversationId'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('equipmentId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('labourId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('renterId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('startDate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('endDate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('totalAmount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('deliveryAddress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deliveryLat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deliveryLng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cancellationReason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('cancelledBy', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endTime', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('platformFee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('pricePerDay', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('startTime', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('totalDays', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'REJECTED', name='BookingStatus'), server_default=sa.text('\'PENDING\'::"BookingStatus"'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['equipmentId'], ['equipment.id'], name=op.f('booking_equipmentId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['labourId'], ['labour_profile.id'], name=op.f('booking_labourId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['renterId'], ['user.id'], name=op.f('booking_renterId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_pkey'))
    )
    op.create_index(op.f('booking_status_idx'), 'booking', ['status'], unique=False)
    op.create_index(op.f('booking_renterId_idx'), 'booking', ['renterId'], unique=False)
    op.create_index(op.f('booking_labourId_idx'), 'booking', ['labourId'], unique=False)
    op.create_index(op.f('booking_equipmentId_idx'), 'booking', ['equipmentId'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bookingId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('raisedBy', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('againstUser', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evidenceImages', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'IN_REVIEW', 'RESOLVED', 'CLOSED', name='DisputeStatus'), autoincrement=False, nullable=False),
    sa.Column('resolution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolvedBy', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolvedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['againstUser'], ['user.id'], name=op.f('disputes_againstUser_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bookingId'], ['booking.id'], name=op.f('disputes_bookingId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raisedBy'], ['user.id'], name=op.f('disputes_raisedBy_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('disputes_pkey'))
    )
    op.create_index(op.f('disputes_bookingId_idx'), 'disputes', ['bookingId'], unique=False)
    op.create_table('dm_conversations',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('participant1Id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('participant2Id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('lastMessage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lastMessageAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('lastMessageSenderId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['participant1Id'], ['user.id'], name=op.f('dm_conversations_participant1Id_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['participant2Id'], ['user.id'], name=op.f('dm_conversations_participant2Id_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('dm_conversations_pkey'))
    )
    op.create_index(op.f('dm_conversations_participant1Id_participant2Id_key'), 'dm_conversations', ['participant1Id', 'participant2Id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bookingId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lastMessage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lastMessageAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bookingId'], ['booking.id'], name=op.f('conversations_bookingId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    )
    op.create_index(op.f('conversations_bookingId_key'), 'conversations', ['bookingId'], unique=True)
    op.create_table('session',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ipAddress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('userAgent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('session_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('session_pkey'))
    )
    op.create_index(op.f('session_userId_idx'), 'session', ['userId'], unique=False)
    op.create_index(op.f('session_token_key'), 'session', ['token'], unique=True)
    op.create_table('_ConversationParticipants',
    sa.Column('A', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('B', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['A'], ['conversations.id'], name=op.f('_ConversationParticipants_A_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['B'], ['user.id'], name=op.f('_ConversationParticipants_B_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('A', 'B', name=op.f('_ConversationParticipants_AB_pkey'))
    )
    op.create_index(op.f('_ConversationParticipants_B_index'), '_ConversationParticipants', ['B'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('emailVerified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('isProfileComplete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('isVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('preferredLanguage', sa.TEXT(), server_default=sa.text("'en'::text"), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('RENTER', 'PROVIDER', 'LABOUR', 'ADMIN', name='Role'), server_default=sa.text('\'RENTER\'::"Role"'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('user_role_idx'), 'user', ['role'], unique=False)
    op.create_index(op.f('user_latitude_longitude_idx'), 'user', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('user_isVerified_idx'), 'user', ['isVerified'], unique=False)
    op.create_index(op.f('user_email_key'), 'user', ['email'], unique=True)
    op.create_index(op.f('user_email_idx'), 'user', ['email'], unique=False)
    op.create_index(op.f('user_city_state_idx'), 'user', ['city', 'state'], unique=False)
    op.create_table('verification',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('verification_pkey'))
    )
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    op.create_table('notification',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('isRead', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('actionLabel', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actionUrl', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('eventType', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('priority', sa.TEXT(), server_default=sa.text("'normal'::text"), autoincrement=False, nullable=False),
    sa.Column('readAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('relatedBookingId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('relatedEquipmentId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('relatedUserId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('notification_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_pkey'))
    )
    op.create_index(op.f('notification_userId_idx'), 'notification', ['userId'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('review',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bookingId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('equipmentId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewerId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bookingId'], ['booking.id'], name=op.f('review_bookingId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipmentId'], ['equipment.id'], name=op.f('review_equipmentId_fkey'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewerId'], ['user.id'], name=op.f('review_reviewerId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('review_pkey'))
    )
    op.create_index(op.f('review_reviewerId_idx'), 'review', ['reviewerId'], unique=False)
    op.create_index(op.f('review_rating_createdAt_idx'), 'review', ['rating', 'createdAt'], unique=False)
    op.create_index(op.f('review_equipmentId_idx'), 'review', ['equipmentId'], unique=False)
    op.create_index(op.f('review_bookingId_key'), 'review', ['bookingId'], unique=True)
    op.create_table('payment',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bookingId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.TEXT(), server_default=sa.text("'INR'::text"), autoincrement=False, nullable=False),
    sa.Column('razorpayOrderId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('razorpayPaymentId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('razorpaySignature', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'SUCCESS', 'FAILED', 'REFUNDED', name='PaymentStatus'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bookingId'], ['booking.id'], name=op.f('payment_bookingId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name=op.f('payment_userId_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_pkey'))
    )
    op.create_index(op.f('payment_userId_idx'), 'payment', ['userId'], unique=False)
    op.create_index(op.f('payment_bookingId_key'), 'payment', ['bookingId'], unique=True)
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_labour_services_id'), table_name='labour_services')
    op.drop_table('labour_services')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
