"""add_razorpay_fields

Revision ID: ccaa299a2e49
Revises: 247a8f73e9bb
Create Date: 2026-04-05 16:04:59.902616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccaa299a2e49'
down_revision: Union[str, Sequence[str], None] = '247a8f73e9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('advance_amount', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('remaining_amount', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('payment_status', sa.Enum('pending', 'partially_paid', 'fully_paid', 'failed', name='paymentstatus'), nullable=True))
    op.add_column('users', sa.Column('razorpay_account_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('kyc_status', sa.Enum('pending', 'active', 'rejected', name='kycstatus'), nullable=True))
    op.add_column('users', sa.Column('payout_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payout_enabled')
    op.drop_column('users', 'kyc_status')
    op.drop_column('users', 'razorpay_account_id')
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'remaining_amount')
    op.drop_column('bookings', 'advance_amount')
    # ### end Alembic commands ###
